name: Build
on: [push]
jobs:

  deploy:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          mkdir -p {sources,rpm}
          docker build --build-arg FLB_PREFIX=v --build-arg FLB_VERSION=1.6.7 -t flb .
          docker run --rm -v ${PWD}/rpm:/output -e FLB_VERSION=1.6.7 flb:latest

      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: fluent-bit-centos7
          path: ${{ github.workspace }}/rpm
